### ISSUE TITLE
git checkout failed.

### ISSUE THREAD

**Issue by gvanem** [JvanKatwijk/swradio-8#15]
Due to the file `https://github.com/JvanKatwijk/swradio-8/blob/master/decoders/fax-decoder/:1`, 
a `git clone https://github.com/JvanKatwijk/swradio-8.git .` fails on Windows. It's illegal to have a `:` in a filename.

And I see this is really a .cpp source file which does not seems to be part of this project. Please delete it.
Or do you recommend all Windows users to switch to Linux?

**Comment by JvanKatwijk** [comment]
I would not mind only dealing with Linux users as far as building executables is concerned
As mentioned 1000 times: "software is available "as is"", be happy or not with it, I really do not care
